namespace Last_Music_Player
{
    [default_interface]
    runtimeclass TrackViewModel
    {
        TrackViewModel();
        String Title;
        String Artist;
        Microsoft.UI.Xaml.Media.Imaging.BitmapImage AlbumArt;
        Windows.Storage.StorageFile File;
    }

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
